package telran.problem.dto.kafkaData.commentDataDto;

public enum CommentMethodName {
    ADD_COMMENT,
    ADD_LIKE,
    REMOVE_LIKE,
    ADD_DISLIKE,
    REMOVE_DISLIKE,
    REMOVE_LIKE_REMOVE_COMMENT_ACTIVITY,
    REMOVE_LIKE_REMOVE_ALL_ACTIVITIES,
    REMOVE_DISLIKE_REMOVE_COMMENT_ACTIVITY,
    REMOVE_DISLIKE_REMOVE_ALL_ACTIVITIES,
    DELETE_COMMENT,
    DELETE_COMMENT_AND_PROBLEM
}
